SFOS-1416: ping not working SFOS-440 Add SuSE support from the RPMs

diff --git a/core/release/scripts/etc/rc.d/init.d/smartfrogd b/core/release/scripts/etc/rc.d/init.d/smartfrogd
--- a/core/release/scripts/etc/rc.d/init.d/smartfrogd
+++ b/core/release/scripts/etc/rc.d/init.d/smartfrogd
@@ -25,7 +25,33 @@
 
 
 # Source function library.
-. /etc/rc.d/init.d/functions
+#. /etc/rc.d/init.d/functions
+
+# Look for LSB and RHEL function scripts
+
+if [ -f /lib/lsb/init-functions ]; then
+  . /lib/lsb/init-functions
+  STOP_SUPPORTED=0
+  alias START_DAEMON=start_daemon
+#  alias STOP_DAEMON=echo "ignoring stop daemon request"
+  alias STATUS=MyStatus
+  alias LOG_SUCCESS=log_success_msg
+  alias LOG_FAILURE=log_failure_msg
+  alias LOG_WARNING=log_warning_msg
+elif [ -f /etc/init.d/functions ]; then
+  . /etc/init.d/functions
+  STOP_SUPPORTED=1
+  #alias START_DAEMON=daemon
+  alias START_DAEMON=start
+  alias STOP_DAEMON=stop
+  alias STATUS=status
+  alias LOG_SUCCESS=success
+  alias LOG_FAILURE=failure
+  alias LOG_WARNING=passed
+else
+  echo "Error: your platform is not supported by $0" > /dev/stderr
+  exit 1
+fi
 
 RETVAL=0
 
@@ -44,6 +70,7 @@ export DISPLAY
 ProgName="SmartFrog Daemon"
 ProgDir="$$SFHOME/bin"
 ProgBin="sfDaemon"
+ProgPing="sfPing"
 Filename="smartfrogd"
 LockFile="/var/lock/subsys/$$ProgBin"
 RunFile=/var/run/$$ProgBin.pid
@@ -61,7 +88,7 @@ function start() {
 	# is it already running
 	status $$ProgBin >/dev/null 2>&1
 	if [ $$? -eq 0 ]; then
-	    return 0
+    return 0
 	fi;
 
 	echo -n "Starting $$ProgName: "
@@ -73,11 +100,11 @@ function start() {
 	nohup $$ProgDir/$$ProgBin -headless >>$$ProgLog  2>&1 &
 	RETVAL=$$?
 	if [ $$RETVAL -eq 0 ]; then
-	    success
-	    touch $$LockFile
+    $LOG_SUCCESS
+    touch $$LockFile
 	else
-	    failure
-	    fi;
+    $LOG_FAILURE
+    fi;
 	echo
 	return $$RETVAL
 }
@@ -95,69 +122,77 @@ function stop() {
 	
 	RETVAL=$$?
 	[ $$RETVAL -eq 0 ] && rm -f $$LockFile $$RunFile
-	success
-        RETVAL=0
+	$LOG_SUCCESS
+  RETVAL=0
 	echo
 	return $$RETVAL
 }
 
 #check the status and return the LSB-standard exit codes
 function status_check() {
-    echo -n "checking status of $$ProgName: "
-    status $$ProgBin 
-    RETVAL=$$?
+#  echo -n "checking status of $$ProgName: "
+#  $STATUS $$ProgBin 
+#  RETVAL=$$?
+#	if [ $$RETVAL -eq 0 ]; then
+#    $$ProgDir/sfPing localhost
+#    RETVAL=$$?
+#	fi;
+  $$ProgDir/$$ProgPing localhost
+  RETVAL=$$?
+  #failure of the ping
 	if [ $$RETVAL -eq 0 ]; then
-        $$ProgDir/sfPing localhost
-        RETVAL=$$?
-	fi;
-        #failure of the ping
-	if [ $$RETVAL -eq 0 ]; then
-        return 0
-    elif [ -x $$RunFile ]; then
-        #program is dead and /var/run pid file exists
-        RETVAL=1
-        return 1
-    elif [ -x $$LockFile ]; then
-        #program is dead and /var/lock lock file exists
-        RETVAL=2
-        return 2
-    else
-        #assume ps is not running
-        RETVAL=3
-        return 3
-    fi
+    return 0
+  elif [ -x $$RunFile ]; then
+    #program is dead and /var/run pid file exists
+    RETVAL=1
+    return 1
+  elif [ -x $$LockFile ]; then
+    #program is dead and /var/lock lock file exists
+    RETVAL=2
+    return 2
+  else
+    #assume ps is not running
+    RETVAL=3
+    return 3
+  fi
 }
 
 #restart operation just does a stop and a start
 function restart() {
-    stop
+  stop
 	start
 }
 
 # See how we were called.
 case "$$1" in
   start)
-	start
+    echo start
+	  start
 	;;
   stop)
-	stop
+    echo stop
+  	stop
 	;;
   status)
+    echo status
     status_check
-	;;
+	  ;;
   restart)
-	restart
-	;;
+    echo restart
+  	restart
+	  ;;
   reload)
-	restart
-	;;
+    echo reload
+	  restart
+	  ;;
   force-reload)
-	restart
-	;;
+    echo force-reload 
+    restart
+    ;;
   *)
-	echo $$"Usage: $$PROG {start|stop|restart|status|restart|reload|force-reload}"
+	  echo $$"Usage: $$PROG {start|stop|restart|status|restart|reload|force-reload}"
     #invalid or excess argument(s)
-	RETVAL=2
+	  RETVAL=2
 esac
 
 exit $$RETVAL
